plugins {
    id 'java'
    id 'maven-publish'
    id 'io.freefair.lombok' version '9.0.0'
}

dependencies {

    compileOnly('org.slf4j:slf4j-api:2.0.17')
    compileOnly('ch.qos.logback:logback-classic:1.5.34')

    compileOnly('org.springframework:spring-web:7.0.8')

    testImplementation('org.junit.jupiter:junit-jupiter-api:5.11.0')
    testImplementation('org.springframework:spring-web:7.0.8')
    testImplementation('org.mockito:mockito-core:5.2.0')
    testImplementation('org.mockito:mockito-junit-jupiter:5.2.0')

    testRuntimeOnly('org.junit.jupiter:junit-jupiter-engine:5.11.0')
    testRuntimeOnly('org.slf4j:slf4j-api:2.0.17')
    testRuntimeOnly('ch.qos.logback:logback-classic:1.5.34')
}

tasks.register('sourcesJar', Jar) {
    from sourceSets.main.allJava
    archiveClassifier.set('sources')
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact tasks.sourcesJar
        }
    }
}

test {
    useJUnitPlatform()
}
